#!/bin/bash
# Switch the default R to be either sequential or parallel version of MKL for R
f () {
    errcode=$? # save the exit code as the first thing done in the trap function
    echo "R_switch: error code $errcode"
    exit $errcode  # or use some other value or do return instead
}
trap f ERR
MKL_VERSION=${1:-p}
al=/usr/local/analysis_pipeline
if [ "$MKL_VERSION" = "p" ]; then
    # R
    ln -sf /usr/local/bin/R_p /usr/local/bin/R
    ln -sf /usr/local/bin/Rscript_p /usr/local/bin/Rscript
    echo "R is linked to the parallel MKL version"
    # analysis pipeline
    ap="$al"_p
    if [ -e "$ap" ]; then
        if [ -e $al ]; then
           unlink $al
       fi
        ln -sf $ap $al
    fi
elif [ "$MKL_VERSION" = "s" ]; then
    # R
    ln -sf /usr/local/bin/R_s /usr/local/bin/R
    ln -sf /usr/local/bin/Rscript_s /usr/local/bin/Rscript
    echo "R is linked to the sequential MKL version"
    # analysis pipeline
    ap="$al"_s
    if [ -e "$ap" ]; then
        if [ -e $al ]; then
           unlink $al
       fi
        ln -sf $ap $al
    fi
else
    echo "Invalid MKL option - must be p or s ($MKL_VERSION)"
    exit 1
fi
exit 0
